In [2]:
import numpy as np

In [18]:
a = np.arange(12)
print("원본 배열:",a)
print("실수형 반환:", a.astype(float))

b = a.reshape(2,6)
print("2행 6열 형태:", b)

c = a.reshape(3,-1)
print("자동 계산된 형태(3행 4열):",c)

d = a.flatten()
print("1차원 배열로 축소:",d)












원본 배열: [ 0  1  2  3  4  5  6  7  8  9 10 11]
실수형 반환: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
2행 6열 형태: [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
자동 계산된 형태(3행 4열): [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1차원 배열로 축소: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [22]:
# 연습
arr1 = np.array(10)
print("원본배열:",arr1)
print("원본 배열의 데이터 타입:", arr1.dtype)

원본배열: 10
원본 배열의 데이터 타입: int64


In [25]:
arr2 =arr1.astype('float')
print("형 변환 후 배열:", arr2)
print("변환 된 배열의 데이터 타입:", arr2.dtype)



형 변환 후 배열: 10.0
변환 된 배열의 데이터 타입: float64


In [27]:
arr3 = arr1.astype('str')
print("형변환 후 배열:", arr3)
print("변환된 배열의 데이터 타입:", arr3.dtype)

형변환 후 배열: 10
변환된 배열의 데이터 타입: <U21


In [46]:
arr = np.asarray(10,20)
print(arr)

TypeError: Cannot interpret '20' as a data type

In [30]:
# 차원 변환 - reshape() 함수
origin = np.arange(20)
origin

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [33]:
x = origin.reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
x = origin.reshape(3,7)
x

ValueError: cannot reshape array of size 20 into shape (3,7)

In [74]:
# 열의 수에 관계 없이 1행을 갖는 2차원 배열로 재구성
x = np.array(([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]))

y = origin.reshape(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# 원소의 수 계산 후 1차원 배열로 축소하기
row, cols = x.shape
row, cols

(4, 5)

In [51]:
z = origin.reshape(row * cols)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
x = np.array(([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]]))

x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
y = origin.reshape(-1,1)
y

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19]])

In [76]:
y = origin.reshape(-1,2)
y

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [64]:
x = np.arange(12)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
x = origin.reshape(1,-1)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [72]:
y = origin.reshape(2,-1)
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [82]:
origin = np.array(([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]))

print(origin)

x = origin.reshape(-1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]


In [83]:
y = x.reshape(1,-3)
y

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])